services:
  client:
    image: musicians-client
    build:
      context: ./Client
      dockerfile: Dockerfile.debug
    ports:
      - 4200:4200
    volumes:
      - ./Client:/frontend
    # depends_on:
    #   - api

#   api:
#     image: musicians-api
#     build:
#       context: ./MusiciansAPP
#       args:
#         - CONFIG=Debug
#         - API_KEY=2a3bec42612b4eea5ebf2d9cf2106638
#     ports:
#       - 7093:7093
#     volumes:
#       - ./MusiciansAPP:/app
#     depends_on:
#       - db

#   db:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     environment:
#       ACCEPT_EULA: Y
#       MSSQL_SA_PASSWORD: S3cur3P@ssW0rd!
#     ports:
#       - 1433:1433
#     volumes:
#       - musicians-db:/var/opt/mssql

# volumes:
#   musicians-db: